#!/bin/sh
IPTABLES=/sbin/iptables
NAT_IF_NAME={{ if_name|default("eth0") }}

#set -e

if [ "$IFACE" = "$NAT_IF_NAME" ]; then
   $IPTABLES -t nat -A POSTROUTING -o $NAT_IF_NAME -s {{ subnet }} -j MASQUERADE
   $IPTABLES -A FORWARD -p tcp --syn -s {{ subnet }} -j TCPMSS --set-mss {{ mtu }}
fi

exit 0
