- name: install shadowsocks key
  apt_key: url='{{ shadowsocks_libev_repo_key }}' state=present
  tags:
    - ss-server

- name: add shadowsocks repo
  apt_repository: repo='{{ shadowsocks_libev_repo_url }}' state=present
  tags:
    - ss-server

- name: install shadowsocks libev
  apt: pkg=shadowsocks-libev state=installed force=yes
  tags:
    - ss-server

- name: make a symbol link to /opt/ss-server/
  file: src=/usr/bin/ss-server dest=/opt/ss-server/ss-server state=link
  tags:
    - ss-server
