---
#Setup OpenVPN CA / Server Key / Client Key


- name: install openvpn
  action: apt package=openvpn state=present

- name: upload vars file
  action: /usr/share/doc/openvpn/examples/easy-rsa/2.0

